src/App.vue

#7-mainの上の隙間を削除

---

package.json
src/main.ts
yarn.lock

#12 
**Remind: `yarn install`**
(まあPhpStorm/WebStormなら気づいてくれるけどな VSCode環境がどうなのかは知らない)

#12-FontAwesomeのfar,fabを追加

---

src/App.vue

#9 
- `.header` の幅が広すぎたので修正（私が幅を狭めたときにこっちを変え忘れてた…sry）
- `.header` および `main` の余白を調整

#9-.main-wrapperの外でスクロールできない

---

src/App.vue

#22-wrap style that should be scoped

---

src/App.vue
src/components/TopPageButton.vue

#21-z-indexの反乱を鎮圧

---

src/title-type.d.ts
src/titleMixin.ts
src/views/Home.vue
src/views/about.vue
src/views/access.vue
src/views/policy.vue

Componentのメンバ`title`にタイトルを代入すると`document.title`に設定されるようにした

Fix #33 improve title

---

.env.development
.env.production
src/main.ts

Fix #34 : 環境設定の追加

---

.eslintrc.js
src/App.vue
src/shims-tsx.d.ts
src/titleMixin.ts

#43: fix eslint errors

---

package.json
yarn.lock

#47 install @types/js-cookie

---

aspida.config.js
package.json
yarn.lock

APIクライアントであるところのaspidaを使うための設定とパッケージの追加をしました

#45: setup api

---

.github/workflows/test_pull.yml

#58: warningで落ちるようにした

---

src/App.vue
src/apis/@types.ts
src/apis/admin/change_password.ts
src/apis/admin/login.ts
src/apis/admin/user.ts
src/components/AdminLoginModal.vue
src/libs/auth/admin_auth.ts
src/libs/auth/admin_auth_eventhub.ts
src/libs/auth/index.ts
src/libs/auth/jwt.ts

`libs/admin_auth`の`attempt_get_JWT`を呼ぶとログインされていればtokenが、そうでなければログインダイアログを出してログインしてもらいます

#10: 管理者ログイン

---

src/App.vue
src/router/index.ts
src/views/document.vue

#72 リリース前の諸調整

---

src/App.vue

hotfix: make link absolute and use router

---

src/apis/writer/change_password.ts
src/components/AdminChangePasswordModal.vue
src/components/WriterChangePasswordModal.vue
src/libs/auth/admin_auth.ts
src/libs/auth/writer_auth.ts
src/views/blog/admin/admin_top.vue

#82: パスワード変更

---

src/titleMixin.ts
src/views/Home.vue
src/views/about.vue
src/views/access.vue
src/views/blog/admin/admin_top.vue
src/views/blog/admin/manage_path.vue
src/views/blog/admin/new_revision.vue
src/views/blog/admin/path_list.vue
src/views/blog/admin/revision_list.vue
src/views/blog/admin/revision_preview.vue
src/views/blog/article_list.vue
src/views/blog/category_list.vue
src/views/blog/show_article.vue
src/views/document.vue
src/views/policy.vue

ついでに微変更:
- readonlyつける
- 自明な型指定を消す
をした

#59: タイトルがぶっこわれてた

---

src/views/blog/article_list.vue

#93-ブログ本文プレビューのはみ出しの処理

---

src/libs/categories.ts

#95: カテゴリがないときの対応

---

src/views/blog/admin/admin_top.vue

#88: ログイン後の画面更新

---

src/views/blog/admin/manage_path.vue
src/views/blog/admin/path_list.vue
src/views/blog/admin/revision_list.vue
src/views/blog/admin/revision_preview.vue

#90-一覧のアイコン修正

---

src/App.vue
src/views/blog/admin/manage_path.vue
src/views/blog/admin/path_list.vue
src/views/blog/show_article.vue

(その他カテゴリ系の修正を入れました)
カテゴリ内に存在しないものが選びたければchange req出してくださいな

#110: カテゴリを選択式に

---

src/App.vue
src/libs/categories.ts
src/views/blog/admin/manage_path.vue

id: internal
visible:falseでメニュー等に出ないようになっています

#108: 内部生向けカテゴリ

---

src/App.vue

#133: サイドバーを隠す

---

src/views/blog/article_list.vue

#132: ページタイトルが変わらなかった

---

src/apis/images/@utils.ts
src/apis/images/index.ts
src/components/ImageUploadModal.vue
src/views/blog/admin/new_revision.vue

とりあえず動きます、スタイルはまだ(私の仕事じゃない気がする、別ブランチで @su8ru かな)。修正/機能追加してほしければ言ってください

#118: 画像アップロード

---

src/assets/sass/main.scss

#100-引用css

---

src/views/blog/admin/manage_path.vue

idをそのまま表示した
ついでにwatchをつけた。リンク経由じゃ行けないけど念のため ~(別PRにしなさーい!)~

#116 manage_pathのタイトル

---

src/views/blog/article_list.vue

#97-2-アイキャッチ画像が復活してた

---

src/assets/sass/main.scss
src/assets/sass/wide_main_box.scss
src/views/blog/admin/admin_top.vue
src/views/blog/admin/manage_path.vue
src/views/blog/admin/new_revision.vue
src/views/blog/admin/path_list.vue
src/views/blog/admin/revision_list.vue

boxのwidthをむりやり変えてるので環境によってはバグるかもしれないです… 慎重にレビューしていただけるとうれしいです
tableのセルは折り返しを有効にしました 不評なら戻します(なぜこのブランチでやった(だってissueで言及してあるんだもん))

#146 mainを拡げる

---

src/components/Breadcrumb.vue
src/views/about.vue
src/views/access.vue
src/views/blog/admin/admin_top.vue
src/views/blog/admin/manage_path.vue
src/views/blog/admin/new_revision.vue
src/views/blog/admin/path_list.vue
src/views/blog/admin/revision_list.vue
src/views/blog/admin/revision_preview.vue
src/views/blog/article_list.vue
src/views/blog/show_article.vue
src/views/contact.vue
src/views/document.vue
src/views/policy.vue

resolve #131 
最初hrefで実装しちゃったけどRouterで実装し直しました

#131-パンくずリスト

---

public/robots.txt

#168-Twitterbotがクロールできてなかった

---

src/App.vue

#150-create padding in bottom of main

---

src/components/ShareButtons.vue
src/views/blog/show_article.vue

resolve: #130 
gaにevent飛ばすのは諦めた

#130-share button

---

src/App.vue
src/assets/sass/main.scss
src/views/blog/admin/new_revision.vue
src/views/blog/admin/revision_preview.vue
src/views/blog/show_article.vue

#169-PC: 60% mobile: 100%

---

src/views/blog/article_list.vue

保存先はqueryにしました。理由としては、hashにすると要素を探しにいってエラーを吐くため。
ブランチ名がhashのままなのはご愛嬌

#191: paginationのページ保存

---

src/assets/sass/main.scss
src/views/blog/admin/admin_top.vue

fix: #197 
#188 での仕事がいい加減でした。ごめんなさい。

#197 Bootstrap方面の変更が不十分だった

---

package.json
src/libs/string_date.ts
src/views/Home.vue
src/views/blog/admin/manage_path.vue
src/views/blog/admin/path_list.vue
src/views/blog/admin/revision_list.vue
src/views/blog/admin/revision_preview.vue
src/views/blog/article_list.vue
src/views/blog/show_article.vue
yarn.lock

`getStringTime` / `getStringDate` しか思い浮かばなかったんですが、ほかにもまだまとめるべきものってありますか？
置換漏れが怖いのでそのへんも確認お願いします

#194-ひとまとめ

---

src/libs/string_date.ts

#195 日付の表示形式を変えた

---

package.json
src/components/TopPageButton.vue

#207 TopPageButton の色を更新し忘れた

---

src/assets/sass/main.scss

#202: Bootstrapはrootへ。

---

src/views/blog/admin/new_revision.vue

#199: path制約

---

public/dynamic_ogp.php
src/libs/categories.ts

`update` `更新情報`
で追加してみた。
他の名前がよければ言って

#206 更新情報カテゴリ追加

---

src/apis/images/index.ts

aspidaの仕様変更に気付かなかった ごめんなさい…
reqType → reqFormat https://github.com/aspidajs/aspida/commit/b22da5c56bce7946b7e1f294c9b789fe2eef9500#diff-a582e8c0c1e411b14ce3446a48bfc4d4
afb4419 で修正されるべきものでした

#214: 画像アップロードができるようになった

---

src/apis/images/index.ts

画像うp -> develop

---

src/views/blog/admin/revision_preview.vue

#215 set max-width revision preview

---

public/robots.txt

ブログ記事の Allow・内部生向けの Disallow

---

package.json

Release 1.5.3 to dev

---

src/apis/blog/revisions/@types.ts
src/views/blog/admin/manage_path.vue
src/views/blog/admin/revision_preview.vue

queryは現状存在しないのでパス
(labelはhave to fixなのでbugです)

#226: Revisionのユーザ情報をobjectのやつにした

---

public/dynamic_ogp.php
src/App.vue
src/apis/blog/categories/@types.ts
src/apis/blog/categories/index.ts
src/components/Breadcrumb.vue
src/libs/categories.ts
src/views/Home.vue
src/views/blog/admin/manage_path.vue
src/views/blog/admin/path_list.vue
src/views/blog/article_list.vue
src/views/blog/show_article.vue

resolve #225 afes-website/docs#59

#225 get category from api

---

src/App.vue
src/assets/sass/main.scss
src/views/blog/admin/admin_top.vue
src/views/blog/admin/new_revision.vue
src/views/blog/admin/revision_preview.vue
src/views/blog/article_list.vue
src/views/blog/show_article.vue

fix #233 
結局デザイン関連こまごま総まとめになってしまった…
ここ色の統一出来てないとかあったら教えてくだしあ

#233 色の統一とかデザイン関連とか

---

src/apis/blog/revisions/contrib/@types.ts
src/apis/blog/revisions/contrib/index.ts
src/router/index.ts
src/views/blog/new_contrib.vue

#158 寄稿フォーム

---

public/dynamic_ogp.php

#249 寄稿 ogp

---

package.json
src/views/Home.vue

fix: #253 
明らかに変なミスだったので、レビューの段階で気づきたかったなーと思いました

#253 カテゴリー取得がしんでた to master

---

src/components/SpecialAnnouncement.vue
src/views/Home.vue

#259 無期限延期に関する構造化データ

---

src/components/SpecialAnnouncement.vue

#263 構造化データのご機嫌をとる

---

public/dynamic_ogp.php
public/index.html

#264 notebot を追加 / note:card 対応

---

src/libs/auth/admin_auth.ts
src/libs/auth/writer_auth.ts

#269 JWT有効性ちぇっく

---

src/App.vue

#276 dynamic 100vh

---

src/views/blog/admin/manage_path.vue
src/views/blog/admin/new_revision.vue
src/views/blog/new_contrib.vue

blog 周辺に蔓延っていた `<p>` によるラベル付けを駆逐しました。残党いるかも。
close #284

#284 b-form-group

---

src/views/blog/new_contrib.vue

#277 add link to contrib rules page

---

src/apis/blog/articles/@types.ts
src/apis/blog/revisions/@types.ts
src/views/Home.vue
src/views/blog/admin/manage_path.vue
src/views/blog/admin/new_revision.vue
src/views/blog/admin/revision_preview.vue
src/views/blog/article_list.vue
src/views/blog/new_contrib.vue
src/views/blog/show_article.vue

作業忘れがあったら教えて
通常投稿にはHNがつかない前提での実装
close #283

#283 enable handle name

---

src/App.vue

be caused by db978c8 
committer は私です！！大変申し訳ありませんでした！！
close #278

#278 resurrect sns icon links

---

src/views/blog/admin/new_revision.vue
src/views/blog/new_contrib.vue

#292 自由改行関連対応

---

package.json

Relase 1.7.0 to dev

---

package.json
src/views/blog/new_contrib.vue

#297 newContrib preview handle_name

---

package.json
src/views/blog/new_contrib.vue

#297 preview handle name

---

package.json
src/views/blog/new_contrib.vue

#300 handle name

---

package.json
src/views/blog/new_contrib.vue

#300 handle name to dev

---

src/views/blog/admin/path_list.vue

close #282 
この機能無いじゃん とかあったら教えて下さい

path_list の改善

---

package.json
src/libs/markdown.ts
src/types/markdown-it-plugins.d.ts
yarn.lock

#340 sanitizer を消す

---

package.json
src/assets/sass/main.scss
src/components/EmbedModal.vue
src/components/ImageUploadModal.vue
src/components/MarkdownEditor.vue
src/components/MarkdownRenderer.vue
src/libs/markdown.ts
src/libs/markdown_embed.ts
src/main.ts
src/types/twitter-widgets.d.ts
src/views/blog/admin/new_revision.vue
src/views/blog/article_list.vue
src/views/blog/new_contrib.vue
src/views/blog/show_article.vue
yarn.lock

close #325 
こんな Issue だったんだ………知らなかった………

#325 ブログ html 対応 & 埋め込み対応

---

src/components/IntegratedMarkdownEditor.vue
src/components/MarkdownEditor.vue
src/views/blog/admin/new_revision.vue
src/views/blog/new_contrib.vue

#338 Integrated Markdown Editor

---

package.json

Release v2.2.0 to develop

---

src/components/DraftTable.vue
src/views/admin/exh/exh_manage.vue

#348 draft table 内で exh id による絞り込み

---

src/views/admin/draft/draft_preview.vue

#347 教員も preview を見れるように

---

src/App.vue

fix #281 
close #313 
main-wrapper は root scroll
サイドバーは fixed して `overflow-y: auto`
- Chrome 86
- Edge 86
- Safari ←？ @Takeno-hito

#281 サイドバーをスクロール可能にしたぞ！！！！！

---

src/views/admin/exh/exh_list.vue

#354 Preview ボタンを exh list から消した

---

src/views/admin/draft/draft_manage.vue

#342 draft manage の preview ボタンを独立させた

---

package.json

Release v2.2.1 to dev

---

src/App.vue
src/components/Breadcrumb.vue
src/components/ExhibitionCard.vue
src/router/index.ts
src/views/exhibition/exh_list.vue
src/views/exhibition/exh_show.vue
yarn.lock

close #337
- feat: show exhibitions list
- build: upgrade @afes-website/docs (v2.2.12)
- feat: sort exhibitions by room_id
- fix: nowrap tabs
- fix: hover bg
- feat: show room id
- feat: add exhibition show
- feat: show disable exhibitions
- feat: show breadcrumb in exhibition list
- feat: add share buttons

#337 オンライン展示 外部視点

---

package.json
src/views/Home.vue

fix #373
- feat: update top page
- v2.2.4

[hotfix] トップページ文章更新

---

src/views/admin/blog/revision_list.vue

#389 あなたの記事リクエスト一覧を filter
